version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: unless-stopped

  crawlerheadlesslinux:
    build: .
    depends_on:
      - db
